[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "rdprs"
version = "0.1.0"
description = "Efficient implementation of the Ramer-Douglas-Peucker algorithm using Rust and PyO3."
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.maturin]
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
 "pytest>=8.3.4",
]
